import './globals.css'
import type {Metadata} from 'next'
import {Roboto_Mono, Sofia_Sans} from 'next/font/google'

const robotoMono = Roboto_Mono({
    subsets: ['latin'],
    variable: '--font-roboto-mono'
})
const sofiaSans = Sofia_Sans({
    subsets: ['latin'],
    variable: '--font-sofia-sans'
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({children}: { children: React.ReactNode }) {
    return (
        <html lang="en">
        <body className={`${robotoMono.variable} ${sofiaSans.variable}`}>{children}</body>
        </html>
    )
}
